services:
  postgres:
    image: postgres:16
    container_name: healthsync-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: healthsync_alert
      POSTGRES_USER: healthsync_user
      POSTGRES_PASSWORD: healthsync_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
